
services:
  arr-tools:
    image: ghcr.io/l4stidi0t/arr-tools/main:latest
    container_name: arr-tools
    ports:
      - "9050:9000"
    volumes:
      - ${APP_CONFIG_PATH}/arr-tools:/app/backend/data
    restart: ${RESTART_POLICY}

# Environment file for Portainer
env_file: ../../stack.env
