
services:
  arr-tools:
    image: ghcr.io/l4stidi0t/arr-tools/main:latest
    container_name: arr-tools
    ports:
      - "9050:9000"
    volumes:
      - /mnt/cache/appdata/arr-tools:/app/backend/data
