

services:
  web:
    container_name: iqbit
    image: haruvon/iqbit:latest
    restart: unless-stopped
    environment:
      - QBIT_HOST=http://192.168.4.110:8080
      - STANDALONE_SERVER_PORT=8081
    ports:
      - 8081:8081
