

services:
  web:
    container_name: iqbit
    image: haruvon/iqbit:latest
    restart: ${RESTART_POLICY}
    environment:
      - QBIT_HOST=http://${HOST_IP}:8080
      - STANDALONE_SERVER_PORT=8081
    ports:
      - 8081:8081
