
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=Europe/Istanbul
      - PUID=99
      - PGID=100
      - UMASK=022
    ports:
      - 8945:8945
    volumes:
      - /mnt/cache/appdata/pinchflat:/config
      - /mnt/media/data/media/youtube:/downloads