
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=${TZ}
      - PUID=99
      - PGID=100
      - UMASK=${UMASK}
    ports:
      - 8945:8945
    volumes:
      - ${APP_CONFIG_PATH}/pinchflat:/config
      - ${MEDIA_PATH}/media/youtube:/downloads
    restart: ${RESTART_POLICY}