services:
  rclone_rclone:
    image: rclone/rclone:master
    container_name: rclone
    restart: ${RESTART_POLICY}
    network_mode: bridge
    command: rcd --rc-web-gui --rc-addr :5572 --rc-user bayramog --rc-pass 1234567890
    ports:
      - "5572:5572"
    volumes:
      - ${APP_CONFIG_PATH}/rclone:/config/rclone
      - ${APP_CONFIG_PATH}/rclonelogs:/logs
    environment:
      - PHP_TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
