
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=6jaw8E74a8Vazh8AqzBe
    volumes:
      - ${MEDIA_PATH}/media:${DATA_PATH}/media:rw
      - ${APP_CONFIG_PATH}/plex:/config:rw
    restart: ${RESTART_POLICY}

# Environment file for Portainer
env_file: ../../../stack.env
