
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=3000
      - PGID=3000
      - UMASK=022
      - TZ=Europe/Istanbul
      - VERSION=docker
      - PLEX_CLAIM=g8eitxaGWxw-Ky-FgJTM
    volumes:
      - /mnt/mnt/media/data/media:/data/media:rw
      - /mnt/internal-ssd/appdata/plex:/config:rw
    restart: unless-stopped
