
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=claim-zXUvZxD62UYx_QC6oaud
    volumes:
      - ${MEDIA_PATH}/media:${DATA_PATH}/media:rw
      - ${APP_CONFIG_PATH}/plex:/config:rw
    restart: ${RESTART_POLICY}

