services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    network_mode: bridge
    restart: unless-stopped
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/cache/appdata/autobrr:/config:rw
    ports:
      - 7474:7474
