services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    network_mode: bridge
    restart: ${RESTART_POLICY}
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/autobrr:/config:rw
    ports:
      - 7474:7474
