services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    user: 99:100
    environment:
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/user/appdata/autobrr:/config
    ports:
      - 7474:7474