services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest                         # Matterbridge image with the tag latest
    network_mode: host                                        # Ensures the Matter mdns works
    restart: ${RESTART_POLICY}                                           # Ensures the container always restarts automatically
    volumes:
      - ${APP_CONFIG_DATA_PATH}/matterbridge:/root/Matterbridge        # Mounts the Matterbridge plugin directory
      - ${APP_CONFIG_DATA_PATH}/.matterbridge:/root/.matterbridge      # Mounts the Matterbridge storage directory
