services:
  windows:
    image: dockurr/windows
    container_name: windows
    network_mode: bridge
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - VERSION=11
      - DISK_SIZE=128G
      - RAM_SIZE=8G
      - CPU_CORES=4
      - LANGUAGE=Turkish
      - REGION=tr-TR
      - KEYBOARD=tr-TR
      - GPU=Y
    volumes:
      - /mnt/cache/appdata/windowsdocker:/storage:rw
      - /mnt:/data:rw
    devices:
      - /dev/dri
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: unless-stopped
    stop_grace_period: 2m
