
services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 15m"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    tty: true
    command: sync
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/internal-ssd/appdata/plextraktsync:/app/config:rw
