
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: bridge
    environment:
      - PUID=99
      - PGID=100
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/readarr:/config:rw
      - ${MEDIA_PATH}:${DATA_PATH}:rw 
    ports:
      - 8787:8787
    restart: ${RESTART_POLICY}