
services:
  homebridge:
    image: homebridge/homebridge:ubuntu
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /mnt/user/appdata/homebridge:/homebridge
volumes:
  homebridge: