
services:
  homebridge:
    image: homebridge/homebridge:no-avahi
    container_name: homebridge
    restart: ${RESTART_POLICY}
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${APP_CONFIG_PATH}/homebridge:/homebridge
volumes:
  homebridge:
# Environment file for Portainer
env_file: ../../../stack.env
