
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/overseerr:/config:rw
    ports:
      - 5055:5055
    restart: ${RESTART_POLICY}
# Environment file for Portainer
env_file: ../../../stack.env
