
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: bridge
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/user/appdata/overseerr:/config:rw
    ports:
      - 5055:5055
    restart: unless-stopped