
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/sabnzbd:/config:rw
      - ${MEDIA_PATH}/usenet:${DATA_PATH}/usenet:rw
    ports:
      - 8484:8080
    restart: ${RESTART_POLICY}
# Environment file for Portainer
env_file: ../../../stack.env
