
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=3000
      - PGID=3000
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/internal-ssd/appdata/sabnzbd:/config:rw
      - /mnt/mnt/media/data/usenet:/data/usenet:rw
    ports:
      - 8484:8080
    restart: unless-stopped