
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/user/appdata/sabnzbd:/config:rw
      - /mnt/user/data/usenet:/data/usenet:rw
    ports:
      - 8484:8080
    restart: unless-stopped