#!/bin/bash
# setup-onedrive.sh - Helper script to set up rclone with OneDrive

echo "OneDrive Setup Helper"
echo "====================="
echo "This script will help you set up rclone to connect to OneDrive."
echo "Please follow these steps:"
echo ""
echo "1. Run the rclone container with GUI enabled:"
echo "   docker-compose --env-file stack.env -f docker-compose.yml up -d"
echo ""
echo "2. Access the rclone web GUI at http://your-server-ip:5572"
echo "   Username: bayramog"
echo "   Password: 1234567890 (you should change this in rclone.yml)"
echo ""
echo "3. In the web GUI:"
echo "   - Click on 'Configs' tab"
echo "   - Click 'New remote'"
echo "   - Name: onedrive"
echo "   - Type: Microsoft OneDrive"
echo "   - Follow the authentication steps"
echo ""
echo "4. Test your configuration with:"
echo "   docker exec rclone rclone lsd onedrive:"
echo ""
echo "5. Your backups will automatically sync to OneDrive:/Backups/homelab/"
echo ""
echo "For more information, see: https://rclone.org/onedrive/"