services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest                         # Matterbridge image with the tag latest
    network_mode: host                                        # Ensures the Matter mdns works
    restart: always                                           # Ensures the container always restarts automatically
    volumes:
      - "/mnt/user/appdata/matterbridge:/root/Matterbridge"        # Mounts the Matterbridge plugin directory
      - "/mnt/user/appdata/.matterbridge:/root/.matterbridge"      # Mounts the Matterbridge storage directory