
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    network_mode: bridge
    volumes:
      - /mnt/internal-ssd/appdata/recyclarr:/config:rw
    environment:
      - TZ=Europe/Istanbul
      - CRON_SCHEDULE=@hourly
      - UMASK=022
      - PUID=3000
      - PGID=3000
    restart: unless-stopped