
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: '3000:3000'
    network_mode: bridge
    volumes:
      - /mnt/internal-ssd/appdata/recyclarr:/config:rw
    environment:
      - TZ=Europe/Istanbul
      - CRON_SCHEDULE=@hourly
      - UMASK=022
    restart: unless-stopped