
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: '${PUID}:${PGID}'
    network_mode: bridge
    volumes:
      - ${APP_CONFIG_PATH}/recyclarr:/config:rw
    environment:
      - TZ=${TZ}
      - CRON_SCHEDULE=@hourly
      - UMASK=${UMASK}
    restart: ${RESTART_POLICY}
# Environment file for Portainer
env_file: ../../../stack.env
