
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: bridge
    environment:
      - PUID=3000
      - PGID=3000
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/internal-ssd/appdata/prowlarr:/config:rw
    ports:
      - 9696:9696
    restart: unless-stopped