
services:
  watchlistarr:
    image: nylonee/watchlistarr
    container_name: watchlistarr
    network_mode: bridge
    environment:
      PUID: 3000
      PGID: 3000
      UMASK: 022
      TZ: Europe/Istanbul
    volumes:
      - /mnt/internal-ssd/appdata/watchlistarr:/app/config
    restart: unless-stopped
