
services:
  watchlistarr:
    image: nylonee/watchlistarr
    network_mode: bridge
    environment:
      PUID: 99
      PGID: 100
      UMASK: 022
      TZ: Europe/Istanbul
      LOG_LEVEL: DEBUG
    volumes:
      - /mnt/cache/appdata/watchlistarr:/app/config
    restart: unless-stopped
