
services:
  watchlistarr:
    image: nylonee/watchlistarr
    container_name: watchlistarr
    network_mode: bridge
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/watchlistarr:/app/config
    restart: ${RESTART_POLICY}
