services:
  backup:
    image: restic/restic:latest
    container_name: backup
    restart: ${RESTART_POLICY}
    volumes:
      - ${APP_CONFIG_PATH}:/source:ro
      - ${APP_CONFIG_PATH}/backup:/backup
      - ${APP_CONFIG_PATH}/rclone:/rclone-config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - BACKUP_CRON=${BACKUP_CRON:-0 2 * * *}
      - ONEDRIVE_SYNC_ENABLED=${ONEDRIVE_SYNC_ENABLED:-false}
      - RESTIC_REPOSITORY=/backup/repository
    entrypoint: ["/bin/sh", "-c"]
    command: >
      sh -c '
      mkdir -p /backup/repository /backup/logs &&
      apk add --no-cache busybox-suid tzdata curl ca-certificates rclone &&
      restic snapshots --insecure-no-password || restic init --insecure-no-password &&
      if [ -n "$BACKUP_CRON" ]; then
        echo "$BACKUP_CRON sh -c \"restic backup /source --exclude=/source/backup --tag homelab-config --insecure-no-password && restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --prune --insecure-no-password\"" > /tmp/backup-crontab &&
        crontab /tmp/backup-crontab &&
        echo "Cron job set up, starting cron daemon..." &&
        crond -f -l 8;
      else
        echo "Running backup once..." &&
        restic backup /source --exclude=/source/backup --tag homelab-config --insecure-no-password &&
        restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --prune --insecure-no-password;
      fi
      '