services:
  backup:
    image: alpine:latest
    container_name: backup
    restart: ${RESTART_POLICY}
    volumes:
      # Mount app data directories to backup
      - ${APP_CONFIG_PATH}:/data/appdata:ro
      # Mount backup scripts and output directories
      - ./backup/scripts:/scripts
      - ${APP_CONFIG_PATH}/backups:/backups
      # Mount rclone config to enable OneDrive sync
      - ${APP_CONFIG_PATH}/rclone:/rclone_config:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - BACKUP_RETENTION=${BACKUP_RETENTION:-7}  # Number of days to keep backups
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-"0 2 * * *"}  # Run at 2 AM every day
      - ONEDRIVE_SYNC=${ONEDRIVE_SYNC:-true}  # Enable sync to OneDrive
      - APP_CONFIG_PATH=${APP_CONFIG_PATH}
    entrypoint: /bin/sh
    command: -c "apk add --no-cache bash tar gzip rclone tzdata && \
                  chmod +x /scripts/*.sh && \
                  echo \"${BACKUP_SCHEDULE} /scripts/backup.sh >> /backups/backup.log 2>&1\" > /etc/crontabs/root && \
                  crond -f -d 8"
    networks:
      - default