services:
  backup:
    image: alpine:latest
    container_name: backup
    restart: unless-stopped
    volumes:
      # Mount app data directories to backup
      - /mnt/cache/appdata:/data/appdata:ro
      - /mnt/user/appdata:/data/user_appdata:ro
      # Mount backup scripts and output directories
      - ./backup/scripts:/scripts
      - /mnt/cache/backups:/backups
      # Mount rclone config to enable OneDrive sync
      - /mnt/cache/appdata/rclone:/rclone_config:ro
    environment:
      - TZ=${TZ:-Europe/Istanbul}
      - BACKUP_RETENTION=7  # Number of days to keep backups
      - BACKUP_SCHEDULE="0 2 * * *"  # Run at 2 AM every day
      - ONEDRIVE_SYNC=true  # Enable sync to OneDrive
    entrypoint: /bin/sh
    command: -c "apk add --no-cache bash tar gzip rclone tzdata && \
                  chmod +x /scripts/*.sh && \
                  echo \"${BACKUP_SCHEDULE} /scripts/backup.sh >> /backups/backup.log 2>&1\" > /etc/crontabs/root && \
                  crond -f -d 8"
    networks:
      - default