
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: bridge
    environment:
      - PUID=3000
      - PGID=3000
      - UMASK=022
      - TZ=Europe/Istanbul
      - WEBUI_PORT=8080
    volumes:
      - /mnt/internal-ssd/appdata/qbittorrent:/config:rw
      - /mnt/mnt/media/data/torrents:/data/torrents:rw #optional
    ports:
      - 8080:8080
    restart: unless-stopped