
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${APP_CONFIG_PATH}/qbittorrent:/config:rw
      - ${MEDIA_PATH}/torrents:${DATA_PATH}/torrents:rw #optional
    ports:
      - 8080:8080
    restart: ${RESTART_POLICY}
# Environment file for Portainer
env_file: ../../../stack.env
