
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: bridge
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/cache/appdata/sonarr:/config
      - /mnt/media/data:/data 
    ports:
      - 8989:8989
    restart: unless-stopped