
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:${DATA_PATH} 
    ports:
      - 8989:8989
    restart: ${RESTART_POLICY}