
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: bridge
    environment:
      - PUID=3000
      - PGID=3000
      - UMASK=022
      - TZ=Europe/Istanbul
    volumes:
      - /mnt/internal-ssd/appdata/radarr:/config:rw
      - /mnt/mnt/media/data:/data:rw 
    ports:
      - 7878:7878
    restart: unless-stopped