
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${APP_CONFIG_PATH}/radarr:/config:rw
      - ${MEDIA_PATH}:${DATA_PATH}:rw 
    ports:
      - 7878:7878
    restart: ${RESTART_POLICY}
