

services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    ports:
      - "8789:8789"  # WebDAV erişim portu
    volumes:
      - /mnt/backup/webdav:/var/lib/sftpgo  # Gömülü SQLite ve diğer veriler için
    environment:
      - SFTPGO_ENABLE_WEBDAV=true
      - SFTPGO_WEBDAV_BIND_ADDR=:8789
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}

    restart: ${RESTART_POLICY}

# Environment file for Portainer
env_file: ../../stack.env

