
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/cache/appdata/watchtower:/:rw
    command: --interval 30
