
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    environment:
      - PUID=3000
      - PGID=3000
      - UMASK=022
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
