services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # Gluetun web arayüzü için (isteğe bağlı)
      - "8888:8000"
    environment:
      # PrivadoVPN built-in desteği
      - VPN_SERVICE_PROVIDER=privado
      - VPN_TYPE=openvpn
      - OPENVPN_USER=nhpegakzkkqt
      - OPENVPN_PASSWORD=mfI+S0c[>R=4
      # Server seçimi (isteğe bağlı)
      - SERVER_COUNTRIES=Netherlands  # veya Turkey, Germany vs.
      # DNS ayarları
      - DNS_KEEP_NAMESERVER=off
      - DNS_ADDRESS=1.1.1.1,8.8.8.8
      - DOT=off
      # Firewall ayarları - yerel ağlara erişim
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
    volumes:
      - /mnt/internal-ssd/apps/vpn:/gluetun
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://www.google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
