services:
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/matt8707/ha-fusion:latest
    volumes:
      - ${APP_CONFIG_DATA_PATH}/ha-fusion:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: ${TZ}
      HASS_URL: ${HASS_URL}:8123
    restart: ${RESTART_POLICY}